export interface MockUser {
  id: string
  name: string
  age: number
  town: string
  distanceMiles: number
  bio: string
  avatar: string
  interests: Array<{ interestId: string; level: number }>
  availability: string[]
}

export const MOCK_USERS: MockUser[] = [
  {
    id: 'm1',
    name: 'Margaret',
    age: 68,
    town: 'Riverside',
    distanceMiles: 0.8,
    bio: 'Retired teacher, always got a new book on the go.',
    avatar: 'https://randomuser.me/api/portraits/women/12.jpg',
    interests: [
      { interestId: 'reading', level: 9 },
      { interestId: 'gardening', level: 7 },
      { interestId: 'cards', level: 5 },
    ],
    availability: ['mon-morning', 'wed-afternoon'],
  },
  {
    id: 'm2',
    name: 'Tom',
    age: 71,
    town: 'Oakfield',
    distanceMiles: 12.4,
    bio: 'Ex-postman. Still walk further than my dog wants to.',
    avatar: 'https://randomuser.me/api/portraits/men/11.jpg',
    interests: [
      { interestId: 'walking', level: 10 },
      { interestId: 'birdwatching', level: 8 },
      { interestId: 'history', level: 4 },
    ],
    availability: ['tue-evening', 'thu-morning', 'sat-afternoon'],
  },
  {
    id: 'm3',
    name: 'Priya',
    age: 64,
    town: 'Riverside',
    distanceMiles: 1.6,
    bio: 'Learning to make my grandmother\'s recipes properly.',
    avatar: 'https://randomuser.me/api/portraits/women/23.jpg',
    interests: [
      { interestId: 'cooking', level: 9 },
      { interestId: 'crafts', level: 6 },
      { interestId: 'music', level: 5 },
    ],
    availability: ['mon-afternoon', 'fri-evening'],
  },
  {
    id: 'm4',
    name: 'Derek',
    age: 75,
    town: 'Millbrook',
    distanceMiles: 3.2,
    bio: 'Chess on Tuesdays, complaints about the weather every day.',
    avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
    interests: [
      { interestId: 'chess', level: 10 },
      { interestId: 'history', level: 8 },
      { interestId: 'reading', level: 6 },
    ],
    availability: ['wed-morning', 'sun-afternoon', 'thu-evening'],
  },
  {
    id: 'm5',
    name: 'Sheila',
    age: 66,
    town: 'Riverside',
    distanceMiles: 2.1,
    bio: 'Grandkids keep me young. So does line dancing.',
    avatar: 'https://randomuser.me/api/portraits/women/34.jpg',
    interests: [
      { interestId: 'dancing', level: 9 },
      { interestId: 'grandkids', level: 10 },
      { interestId: 'music', level: 7 },
    ],
    availability: ['tue-morning', 'sat-morning'],
  },
  {
    id: 'm6',
    name: 'Frank',
    age: 79,
    town: 'Elmswood',
    distanceMiles: 18.7,
    bio: 'Allotment keeps me out of trouble most days.',
    avatar: 'https://randomuser.me/api/portraits/men/33.jpg',
    interests: [
      { interestId: 'gardening', level: 10 },
      { interestId: 'birdwatching', level: 6 },
      { interestId: 'walking', level: 5 },
    ],
    availability: ['mon-evening', 'wed-evening', 'fri-morning'],
  },
  {
    id: 'm7',
    name: 'Carol',
    age: 62,
    town: 'Millbrook',
    distanceMiles: 3.9,
    bio: 'Trying to finally understand this smartphone.',
    avatar: 'https://randomuser.me/api/portraits/women/45.jpg',
    interests: [
      { interestId: 'tech', level: 8 },
      { interestId: 'crafts', level: 7 },
      { interestId: 'volunteering', level: 6 },
    ],
    availability: ['thu-afternoon', 'sun-morning'],
  },
  {
    id: 'm8',
    name: 'Ray',
    age: 70,
    town: 'Riverside',
    distanceMiles: 0.4,
    bio: 'Local history buff, will talk your ear off about the old mill.',
    avatar: 'https://randomuser.me/api/portraits/men/44.jpg',
    interests: [
      { interestId: 'history', level: 10 },
      { interestId: 'reading', level: 7 },
      { interestId: 'walking', level: 6 },
    ],
    availability: ['tue-afternoon', 'fri-afternoon', 'sat-evening'],
  },
  {
    id: 'm9',
    name: 'Angela',
    age: 65,
    town: 'Elmswood',
    distanceMiles: 16.2,
    bio: 'Swim club three mornings a week, rain or shine.',
    avatar: 'https://randomuser.me/api/portraits/women/56.jpg',
    interests: [
      { interestId: 'swimming', level: 9 },
      { interestId: 'travel', level: 7 },
      { interestId: 'cooking', level: 5 },
    ],
    availability: ['mon-morning', 'thu-morning'],
  },
  {
    id: 'm10',
    name: 'George',
    age: 73,
    town: 'Oakfield',
    distanceMiles: 11.8,
    bio: 'Volunteer driver, always up for a day trip.',
    avatar: 'https://randomuser.me/api/portraits/men/55.jpg',
    interests: [
      { interestId: 'volunteering', level: 9 },
      { interestId: 'travel', level: 8 },
      { interestId: 'cards', level: 6 },
    ],
    availability: ['wed-afternoon', 'sat-afternoon', 'sun-evening'],
  },
  {
    id: 'm11',
    name: 'Walter',
    age: 74,
    town: 'Millbrook',
    distanceMiles: 5.6,
    bio: 'The woodworking shed is my happy place.',
    avatar: 'https://randomuser.me/api/portraits/men/66.jpg',
    interests: [
      { interestId: 'woodworking', level: 9 },
      { interestId: 'chess', level: 6 },
      { interestId: 'pub_quiz', level: 5 },
    ],
    availability: ['mon-morning', 'wed-afternoon'],
  },
  {
    id: 'm12',
    name: 'Doris',
    age: 69,
    town: 'Oakfield',
    distanceMiles: 9.3,
    bio: 'Choir practice Tuesdays, gossip included.',
    avatar: 'https://randomuser.me/api/portraits/women/67.jpg',
    interests: [
      { interestId: 'choir', level: 9 },
      { interestId: 'singing', level: 7 },
      { interestId: 'theatre', level: 5 },
    ],
    availability: ['tue-evening', 'thu-morning', 'sat-afternoon'],
  },
  {
    id: 'm13',
    name: 'Alan',
    age: 72,
    town: 'Riverside',
    distanceMiles: 1.2,
    bio: 'Fixing up an old motorbike in the garage.',
    avatar: 'https://randomuser.me/api/portraits/men/77.jpg',
    interests: [
      { interestId: 'motorcycling', level: 9 },
      { interestId: 'classic_cars', level: 7 },
      { interestId: 'tech', level: 4 },
    ],
    availability: ['mon-afternoon', 'fri-evening'],
  },
  {
    id: 'm14',
    name: 'Jean',
    age: 77,
    town: 'Elmswood',
    distanceMiles: 14.5,
    bio: 'Beekeeping since 1998, ask me anything.',
    avatar: 'https://randomuser.me/api/portraits/women/78.jpg',
    interests: [
      { interestId: 'beekeeping', level: 10 },
      { interestId: 'allotment', level: 7 },
      { interestId: 'composting', level: 6 },
    ],
    availability: ['wed-morning', 'sun-afternoon', 'thu-evening'],
  },
  {
    id: 'm15',
    name: 'Vic',
    age: 68,
    town: 'Millbrook',
    distanceMiles: 4.1,
    bio: 'Sunday snooker league, no excuses.',
    avatar: 'https://randomuser.me/api/portraits/men/88.jpg',
    interests: [
      { interestId: 'snooker', level: 9 },
      { interestId: 'darts', level: 6 },
      { interestId: 'pub_quiz', level: 6 },
    ],
    availability: ['tue-morning', 'sat-morning'],
  },
  {
    id: 'm16',
    name: 'Pauline',
    age: 63,
    town: 'Riverside',
    distanceMiles: 0.9,
    bio: 'Jigsaw puzzles take over my dining table.',
    avatar: 'https://randomuser.me/api/portraits/women/15.jpg',
    interests: [
      { interestId: 'jigsaw_puzzles', level: 9 },
      { interestId: 'crossword', level: 7 },
      { interestId: 'sudoku', level: 6 },
    ],
    availability: ['mon-evening', 'wed-evening', 'fri-morning'],
  },
  {
    id: 'm17',
    name: 'Norman',
    age: 80,
    town: 'Oakfield',
    distanceMiles: 10.6,
    bio: 'Model railway in the loft, always growing.',
    avatar: 'https://randomuser.me/api/portraits/men/10.jpg',
    interests: [
      { interestId: 'model_trains', level: 10 },
      { interestId: 'photography', level: 5 },
      { interestId: 'history', level: 6 },
    ],
    availability: ['thu-afternoon', 'sun-morning'],
  },
  {
    id: 'm18',
    name: 'Yvonne',
    age: 66,
    town: 'Riverside',
    distanceMiles: 2.8,
    bio: 'Flower arranging club treasurer.',
    avatar: 'https://randomuser.me/api/portraits/women/26.jpg',
    interests: [
      { interestId: 'flower_arranging', level: 9 },
      { interestId: 'gardening', level: 7 },
      { interestId: 'art_gallery', level: 5 },
    ],
    availability: ['tue-afternoon', 'fri-afternoon', 'sat-evening'],
  },
  {
    id: 'm19',
    name: 'Colin',
    age: 71,
    town: 'Elmswood',
    distanceMiles: 17.9,
    bio: 'Sea fishing whenever the weather allows.',
    avatar: 'https://randomuser.me/api/portraits/men/21.jpg',
    interests: [
      { interestId: 'fishing', level: 10 },
      { interestId: 'sailing', level: 6 },
      { interestId: 'wildlife', level: 5 },
    ],
    availability: ['mon-morning', 'thu-morning'],
  },
  {
    id: 'm20',
    name: 'Brenda',
    age: 74,
    town: 'Millbrook',
    distanceMiles: 6.4,
    bio: 'Quilting group meets fortnightly.',
    avatar: 'https://randomuser.me/api/portraits/women/37.jpg',
    interests: [
      { interestId: 'quilting', level: 9 },
      { interestId: 'sewing', level: 7 },
      { interestId: 'crafts', level: 6 },
    ],
    availability: ['wed-afternoon', 'sat-afternoon', 'sun-evening'],
  },
  {
    id: 'm21',
    name: 'Trevor',
    age: 69,
    town: 'Riverside',
    distanceMiles: 1.9,
    bio: 'Bell ringing on Sundays, walking the rest of the week.',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    interests: [
      { interestId: 'bell_ringing', level: 9 },
      { interestId: 'walking', level: 6 },
      { interestId: 'history', level: 5 },
    ],
    availability: ['mon-morning', 'wed-afternoon'],
  },
  {
    id: 'm22',
    name: 'Wendy',
    age: 65,
    town: 'Oakfield',
    distanceMiles: 11.3,
    bio: 'Karaoke nights are non-negotiable.',
    avatar: 'https://randomuser.me/api/portraits/women/48.jpg',
    interests: [
      { interestId: 'karaoke', level: 9 },
      { interestId: 'singing', level: 7 },
      { interestId: 'dancing', level: 6 },
    ],
    availability: ['tue-evening', 'thu-morning', 'sat-afternoon'],
  },
  {
    id: 'm23',
    name: 'Ken',
    age: 76,
    town: 'Riverside',
    distanceMiles: 3.5,
    bio: 'Archery club on weekends, steady hands still.',
    avatar: 'https://randomuser.me/api/portraits/men/43.jpg',
    interests: [
      { interestId: 'archery', level: 9 },
      { interestId: 'fencing', level: 5 },
      { interestId: 'martial_arts', level: 5 },
    ],
    availability: ['mon-afternoon', 'fri-evening'],
  },
  {
    id: 'm24',
    name: 'Maureen',
    age: 70,
    town: 'Elmswood',
    distanceMiles: 15.8,
    bio: 'Cheese making is my retirement project.',
    avatar: 'https://randomuser.me/api/portraits/women/59.jpg',
    interests: [
      { interestId: 'cheese_making', level: 9 },
      { interestId: 'cooking', level: 7 },
      { interestId: 'brewing', level: 5 },
    ],
    availability: ['wed-morning', 'sun-afternoon', 'thu-evening'],
  },
  {
    id: 'm25',
    name: 'Stan',
    age: 73,
    town: 'Millbrook',
    distanceMiles: 4.9,
    bio: 'Stargazing with a flask of tea, best hobby going.',
    avatar: 'https://randomuser.me/api/portraits/men/54.jpg',
    interests: [
      { interestId: 'stargazing', level: 9 },
      { interestId: 'astronomy', level: 8 },
      { interestId: 'tea', level: 5 },
    ],
    availability: ['tue-morning', 'sat-morning'],
  },
]
